/* Copyright (c) 2026 Burak Yazar */

#ifndef RNDR_H
#define RNDR_H

/* RNDR.H - Main header for rendering module */
#include "../GFX/VGA.H"

#include "../MESH/CMS.H"
#include "../RNDR/LIGHT.H"
#include "../RNDR/CAMER.H"
#include "../RNDR/FONT.H"
#include "../RNDR/SPRIT.h"
#include "../RNDR/TRIMES.H"
#include "../RNDR/ANIM.H"
#include "../RNDR/PRTCL.H"
#include "../RNDR/BBOARD.H"
#include "../RNDR/GUI.H"
#include "../RNDR/SKY.H"

#endif /* RNDR_H */
